services:
  - type: web
    name: discord-rpc-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TOKEN
        sync: false
      - key: PORT
        value: 5000
